---
title: "Writing Functions"
author: "Eileen Shea"
date: "11/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

library(tidyverse)
library(rvest)

set.seed(1)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Let's write some functions

Start small!

```{r}
x = rnorm(25, mean = 5, sd = 3)

(x - mean(x)) / sd(x)
```

Write a function to compute z scores for a vector.

```{r}
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  z
  
}
```

Check to see if this works...

```{r}
unif_sample = runif(100)

z_scores(x = unif_sample)
```

Put some checks on inputs...

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
 (x - mean(x)) / sd(x)
  
}
```

## Multiple outputs (mean and sd)

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}

mean_and_sd(unif_sample)
```

## Multiple inputs

Look at simple linear regression!

```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]
```

Write a function that simulates data, fits the model, and returns the estimates. Inputs are sample size and true coefficients.

```{r}
sim_regression = function(n, beta0 = 2, beta1 = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}
```

```{r}
sim_regression(n = 3000, beta0 = 0, beta1 = -1)

sim_regression(n = 3000)

sim_regression(n = 300, beta0 = 2, beta = 5)
```

